EmptyMVC/Models/Base.cs
using System;
namespace EmptyMVC.Models
{
    public class Base
    {
        public int Id { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public double Price { get; set; }
        public int CategoryId { get; set; }
    }
}

EmptyMVC/Models/Category.cs
using System;
namespace EmptyMVC.Models
{
    public class Category
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

EmptyMVC/Models/Computer.cs
using System;
namespace EmptyMVC.Models
{
    public class Computer : Base
    {
    }
}

EmptyMVC/Models/Phone.cs
using System;
namespace EmptyMVC.Models
{
    public class Phone: Base
    {
        
    }
}

EmptyMVC/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EmptyMVC.DataAccess;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace EmptyMVC.Controllers
{
    public class CategoryController : Controller
    {
        private readonly PhoneDbContext _context;
        public CategoryController(PhoneDbContext context)
        {
            _context = context;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            var categories = _context.Categories.ToList();
            return View(categories);
        }

        

    }
}

EmptyMVC/Controllers/ComputerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EmptyMVC.DataAccess;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;


namespace EmptyMVC.Controllers
{
    public class ComputerController : Controller
    {
        private readonly PhoneDbContext _context;
        public ComputerController(PhoneDbContext context)
        {
            _context = context;
        }
        // GET: /<controller>/
        //public async Task<IActionResult> Index()
        //{
        //    return View(await _context.Computers.ToListAsync());
        //}

        public async Task<IActionResult> Index(string brand)
        {
            if (brand == null)
            {
                var comps = await _context.Computers.ToListAsync();
                return View(comps);
            }

            var computers = await _context.Computers.Where(x => x.Brand == brand).ToListAsync();
            return View(computers);
        }
    }
}

EmptyMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace EmptyMVC.Controllers
{
    public class HomeController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

EmptyMVC/Controllers/PhoneController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EmptyMVC.DataAccess;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace EmptyMVC.Controllers
{
    public class PhoneController : Controller
    {
        private readonly PhoneDbContext _context;
        public PhoneController(PhoneDbContext context)
        {
            _context = context;
        }
        //PhoneDbContext _context = new PhoneDbContext();
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View(_context.Phones.ToList());
        }
    }
}

EmptyMVC/ViewComponents/FooterViewComponent.cs
using System;
using Microsoft.AspNetCore.Mvc;

namespace EmptyMVC.ViewComponents
{
    public class FooterViewComponent: ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View("Default");
        }
    }
}

EmptyMVC/ViewComponents/NavbarViewComponent.cs
using System;
using EmptyMVC.DataAccess;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EmptyMVC.ViewComponents
{
    [ViewComponent(Name = "Navbar")]
    public class NavbarViewComponent : ViewComponent
    {
        
        public IViewComponentResult Invoke()
        {
            return View("Default");
        }

    }
}

EmptyMVC/Views/Category/Index.cshtml
@model IEnumerable<Category>

@Html.Partial("_ListPartialView", Model)

EmptyMVC/Views/Category/_CategoryListPartialView.cshtml
@model IEnumerable<Category>

@foreach (var item in Model)
{
    <div class="card" style="width: 18rem;">
        <div class="card-header">
            @Html.DisplayFor(modelItem => item.Name)
        </div>
    </div>
}

EmptyMVC/Views/Computer/Details.cshtml
@model IEnumerable<Computer>

@foreach (var item in Model)
{
    <div class="card" style="width: 18rem;">
        <div class="card-header">
            @Html.DisplayFor(modelItem => item.Model)
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">BRAND: @Html.DisplayFor(modelItem => item.Brand)</li>
            <li class="list-group-item">PRICE: @Html.DisplayFor(modelItem => item.Price)</li>
        </ul>
    </div>
}

EmptyMVC/Views/Computer/Index.cshtml
@model IEnumerable<Computer>

@Html.Partial("_ListPartialView", Model)

EmptyMVC/Views/Computer/_ComputerListPartialView.cshtml
@model IEnumerable<Computer>

@foreach (var item in Model)
{
    <div class="card" style="width: 18rem;">
        <div class="card-header">
            @Html.DisplayFor(modelItem => item.Model)
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">BRAND: @Html.DisplayFor(modelItem => item.Brand)</li>
            <li class="list-group-item">PRICE: @Html.DisplayFor(modelItem => item.Price)</li>
        </ul>
    </div>
 }

EmptyMVC/Views/Home/Index.cshtml
@*@await Component.InvokeAsync("Footer")*@

EmptyMVC/Views/Phone/Index.cshtml
@model IEnumerable<Phone>



@Html.Partial("_ListPartialView", Model)

EmptyMVC/Views/Phone/_PhoneListPartialView.cshtml
@model IEnumerable<object>


@*@foreach (var item in Model)
{
    <div class="card" style="width: 18rem;">
        <div class="card-header">
            @Html.DisplayFor(modelItem => item.Model)
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">BRAND: @Html.DisplayFor(modelItem => item.Brand)</li>
            <li class="list-group-item">PRICE: @Html.DisplayFor(modelItem => item.Price)</li>
        </ul>
    </div>
}*@

@foreach (var phone in Model)
    {
        @foreach (var item in phone.GetType().GetProperties())
            {
                Console.WriteLine(@item.Name);
                Console.WriteLine(@item.GetValue(phone));

            }

        @*var propValue = @prop.GetValue(Model, null);*@
    @*<div class="card" style="width: 18rem;">
        <div class="card-header">
            @Html.DisplayFor(modelItem => item.Model)
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">BRAND: @Html.DisplayFor(modelItem => item.Brand)</li>
            <li class="list-group-item">PRICE: @Html.DisplayFor(modelItem => item.Price)</li>
        </ul>
    </div>*@
}

@*@foreach (System.Reflection.PropertyInfo prop in Model.GetType().GetProperties())
    {
        var propValue = @prop.GetValue(@Model);
        <div class="form-group">
            <label asp-for="@prop.Name" class="control-label"></label>
            <input asp-for="@propValue" name="@prop.Name" class="form-control" />
            <span asp-validation-for="@prop.Name" class="text-danger"></span>
        </div>
    }*@

EmptyMVC/Views/Shared/Components/Footer/Default.cshtml
<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2022 - MVC Project - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>

EmptyMVC/Views/Shared/Components/Navbar/Default.cshtml
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Dropdown
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                </li>
            </ul>
            <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>

EmptyMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EmptyMVC</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    @await Component.InvokeAsync("Navbar")
    @RenderBody()
    @await Component.InvokeAsync("Footer")
</body>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</html>

EmptyMVC/Views/Shared/_ListPartialView.cshtml
@model IEnumerable<object>

@foreach (var item in Model)
    {

        <div class="card" style="width: 18rem;">
            <div class="card-header">

            </div>
            <ul class="list-group list-group-flush">
                @foreach (var prop in item.GetType().GetProperties())
                    {
                    <li class="list-group-item">@prop.Name :  @prop.GetValue(item)</li>
                    }
                </ul>
        </div>
       }